import xrpl from 'xrpl'
import fs from 'fs'

// Setup script for lending protocol tutorials

process.stdout.write('Setting up tutorial: 0%\r')

const client = new xrpl.Client('wss://lend.devnet.rippletest.net:51233')
await client.connect()

// Lending Devnet info
const faucetHost = 'lend-faucet.devnet.rippletest.net'
const faucetPath = '/accounts'

// Create and fund wallets
const [
  { wallet: loanBroker },
  { wallet: borrower },
  { wallet: depositor },
  { wallet: credentialIssuer }
] = await Promise.all([
  client.fundWallet(null, { faucetHost, faucetPath }),
  client.fundWallet(null, { faucetHost, faucetPath }),
  client.fundWallet(null, { faucetHost, faucetPath }),
  client.fundWallet(null, { faucetHost, faucetPath })
])

process.stdout.write('Setting up tutorial: 20%\r')

// Set up credentials and domain
const credentialType = xrpl.convertStringToHex('KYC-Verified')

await client.submitAndWait({
  TransactionType: 'Batch',
  Account: credentialIssuer.address,
  Flags: xrpl.BatchFlags.tfAllOrNothing,
  RawTransactions: [
    {
      RawTransaction: {
        TransactionType: 'CredentialCreate',
        Account: credentialIssuer.address,
        Subject: loanBroker.address,
        CredentialType: credentialType,
        Flags: xrpl.GlobalFlags.tfInnerBatchTxn
      }
    },
    {
      RawTransaction: {
        TransactionType: 'CredentialCreate',
        Account: credentialIssuer.address,
        Subject: borrower.address,
        CredentialType: credentialType,
        Flags: xrpl.GlobalFlags.tfInnerBatchTxn
      }
    },
    {
      RawTransaction: {
        TransactionType: 'CredentialCreate',
        Account: credentialIssuer.address,
        Subject: depositor.address,
        CredentialType: credentialType,
        Flags: xrpl.GlobalFlags.tfInnerBatchTxn
      }
    },
    {
      RawTransaction: {
        TransactionType: 'PermissionedDomainSet',
        Account: credentialIssuer.address,
        AcceptedCredentials: [
          {
            Credential: {
              Issuer: credentialIssuer.address,
              CredentialType: credentialType
            }
          }
        ],
        Flags: xrpl.GlobalFlags.tfInnerBatchTxn
      }
    }
  ]
}, { wallet: credentialIssuer, autofill: true })

const credentialIssuerObjects = await client.request({
  command: 'account_objects',
  account: credentialIssuer.address,
  ledger_index: 'validated'
})
const domainID = credentialIssuerObjects.result.account_objects.find(node =>
  node.LedgerEntryType === 'PermissionedDomain'
).index

process.stdout.write('Setting up tutorial: 40%\r')

// Accept credentials
await Promise.all(
  [loanBroker, borrower, depositor].map(wallet =>
    client.submitAndWait({
      TransactionType: 'CredentialAccept',
      Account: wallet.address,
      Issuer: credentialIssuer.address,
      CredentialType: credentialType
    }, { wallet, autofill: true })
  )
)

process.stdout.write('Setting up tutorial: 60%\r')

// Create private vault
const vaultCreateResponse = await client.submitAndWait({
  TransactionType: 'VaultCreate',
  Account: loanBroker.address,
  Asset: {
    currency: 'XRP'
  },
  Flags: xrpl.VaultCreateFlags.tfVaultPrivate,
  DomainID: domainID
}, { wallet: loanBroker, autofill: true })

const vaultID = vaultCreateResponse.result.meta.AffectedNodes.find(node => 
  node.CreatedNode?.LedgerEntryType === 'Vault'
).CreatedNode.LedgerIndex

process.stdout.write('Setting up tutorial: 80%\r')

// Create loan broker and deposit XRP into vault
const [loanBrokerSetResponse] = await Promise.all([
  client.submitAndWait({
    TransactionType: 'LoanBrokerSet',
    Account: loanBroker.address,
    VaultID: vaultID
  }, { wallet: loanBroker, autofill: true }),
  client.submitAndWait({
    TransactionType: 'VaultDeposit',
    Account: depositor.address,
    VaultID: vaultID,
    Amount: '50000000'
  }, { wallet: depositor, autofill: true })
])

const loanBrokerID = loanBrokerSetResponse.result.meta.AffectedNodes.find(node => 
  node.CreatedNode?.LedgerEntryType === 'LoanBroker'
).CreatedNode.LedgerIndex

process.stdout.write('Setting up tutorial: 100%\r')

// Write setup data to JSON file
const setupData = {
  description: 'This file is auto-generated by lendingSetup.js. It stores XRPL account info for use in lending protocol tutorials.',
  loanBroker: {
    address: loanBroker.address,
    seed: loanBroker.seed
  },
  borrower: {
    address: borrower.address,
    seed: borrower.seed
  },
  depositor: {
    address: depositor.address,
    seed: depositor.seed
  },
  credentialIssuer: {
    address: credentialIssuer.address,
    seed: credentialIssuer.seed
  },
  domainID,
  vaultID,
  loanBrokerID
}

fs.writeFileSync('lendingSetup.json', JSON.stringify(setupData, null, 2))

process.stdout.write('Setting up tutorial: Complete!\n')

await client.disconnect()
