import json
import sys

from xrpl.clients import JsonRpcClient
from xrpl.models import (
    MPTokenIssuanceCreate,
    MPTokenIssuanceCreateFlag,
    Payment,
)
from xrpl.transaction import submit_and_wait
from xrpl.wallet import Wallet

ACCOUNTS_FILE = "sponsored_fees_and_reserves.json"
GENESIS_SEED = "snoPBrXtMeMyMHUVTgbuqAfg1SUTb"

client = JsonRpcClient("http://localhost:5005")
genesis = Wallet.from_seed(GENESIS_SEED, algorithm="secp256k1")

def fund_account(wallet, name):
    """Fund an account from genesis."""
    fund_tx = Payment(
        account=genesis.address,
        destination=wallet.address,
        amount="100000000",  # 100 XRP
    )
    response = submit_and_wait(fund_tx, client, genesis, autofill=True)
    if response.result["meta"]["TransactionResult"] != "tesSUCCESS":
        print(f"Error funding {name}: {response.result['meta']['TransactionResult']}")
        sys.exit(1)


print("Setting up tutorials: 0/3", end="\r")

# 1. Create and fund issuer ---------------------------------------------------
issuer = Wallet.create()
fund_account(issuer, "issuer")

print("Setting up tutorials: 1/3", end="\r")

# 2. Create MPT issuance ------------------------------------------------------
mpt_create_tx = MPTokenIssuanceCreate(
    account=issuer.address,
    maximum_amount="1000000000000",
    asset_scale=2,
    flags=(
        MPTokenIssuanceCreateFlag.TF_MPT_CAN_TRANSFER
        | MPTokenIssuanceCreateFlag.TF_MPT_CAN_LOCK
        | MPTokenIssuanceCreateFlag.TF_MPT_REQUIRE_AUTH
    ),
    transfer_fee=0,
)
response = submit_and_wait(mpt_create_tx, client, issuer, autofill=True)
if response.result["meta"]["TransactionResult"] != "tesSUCCESS":
    print(f"Error creating MPT: {response.result['meta']['TransactionResult']}")
    sys.exit(1)

mpt_issuance_id = response.result["meta"]["mpt_issuance_id"]

print("Setting up tutorials: 2/3", end="\r")

# 3. Save setup data to JSON --------------------------------------------------
setup_data = {
    "description": "Auto-generated by sponsored_fees_and_reserves_setup.py. "
    "Stores XRPL account info for sponsored fees tutorials.",
    "issuer": {"address": issuer.address, "seed": issuer.seed},
    "mpt_issuance_id": mpt_issuance_id,
}

with open(ACCOUNTS_FILE, "w") as f:
    json.dump(setup_data, f, indent=2)

print("Setting up tutorials: Complete!")
